source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

group :jekyll_plugins do
    gem 'github-pages'
    gem "jekyll-gfm-admonitions"
end

gem "webrick", "~> 1.7"
gem "minima"
gem 'wdm', '>= 0.1.0'